### PR TITLE
Survery class, SurveyManager class, and Question Classes

### PR DESCRIPTION
**Pull request by Kousha-Motazedian**
Added Survey Functionalities with SurveyManager

### CODE REVIEW

**Review by momokaddour — APPROVED** [review]
LGTM

Will be clearer once other classes are in.
Might be a good idea to organize src files into subfolders as well in the future

**Review by AkshayVash1 — APPROVED** [review]
Looks good.

**Review by Bilalbc — APPROVED** [review]
lgmt

**Review by MattPorker — APPROVED** [review]
LGTM!

**Pull request merged**
